version: '2.0'

services:
  notebook:
    image: florentdufour/milvus-example:latest
    container_name: jupyter
    ports:
      - '8888:8888'
    volumes:
      - ./notebook:/home/jovyan
    links:
      - milvus
    networks:
      - milvus

  milvus:
    image: milvusdb/milvus:0.9.1-cpu-d052920-e04ed5
    container_name: milvus
    ports:
      - '19530:19530'
      - '19121:19121'
    volumes:
      - ./milvus/db:/var/lib/milvus/db
      - ./milvus/conf:/var/lib/milvus/conf
      - ./milvus/logs:/var/lib/milvus/logs
      - ./milvus/wal:/var/lib/milvus/wal
    networks:
      - milvus
  
  attu:
    image: zilliz/attu:v2.0.0
    container_name: attu
    environment:
      - MILVUS_URL=milvus:19530
    ports:
      - '8000:3000'
    links:
      - milvus
    networks:
      - milvus

networks:
  milvus: